/*
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTestSuiteScopeProvider extends DelegatingScopeProvider {
}
