/*
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import se.mdh.dva501.testsuite.parser.antlr.internal.InternalTestSuiteParser;
import se.mdh.dva501.testsuite.services.TestSuiteGrammarAccess;

public class TestSuiteParser extends AbstractAntlrParser {

	@Inject
	private TestSuiteGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTestSuiteParser createParser(XtextTokenStream stream) {
		return new InternalTestSuiteParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TestSuite";
	}

	public TestSuiteGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TestSuiteGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
