/*
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TestSuiteAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("se/mdh/dva501/testsuite/parser/antlr/internal/InternalTestSuite.tokens");
	}
}
