<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="productspecific" nsURI="http://www.mdh.se/dva501/productspecific"
    nsPrefix="se.mdh.dva501.productspecific">
  <eClassifiers xsi:type="ecore:EClass" name="Family">
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" lowerBound="1"
        upperBound="-1" eType="#//Product" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productSpecificFunctions"
        lowerBound="1" upperBound="-1" eType="#//ProductSpecificFunction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productSpecificSteps" lowerBound="1"
        upperBound="-1" eType="#//ProductSpecificStep" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signals" lowerBound="1"
        upperBound="-1" eType="#//Signal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systems" lowerBound="1"
        upperBound="-1" eType="#//System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productSpecificFunctions"
        lowerBound="1" upperBound="-1" eType="#//ProductSpecificFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductSpecificFunction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productSpecificSteps" lowerBound="1"
        upperBound="-1" eType="#//ProductSpecificStep"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" lowerBound="1"
        upperBound="-1" eType="#//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductSpecificStep" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" eType="#//System"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductSpecificInput" eSuperTypes="#//ProductSpecificStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProductSpecificOutput" eSuperTypes="#//ProductSpecificStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="Signal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
