/*
 * generated by Xtext 2.20.0
 */
package se.mdh.dva501.testsuite;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TestSuiteRuntimeModule extends AbstractTestSuiteRuntimeModule {
}
