/*
 * generated by Xtext 2.20.0
 */
package se.mdh.dva501.testsuite;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TestSuiteStandaloneSetup extends TestSuiteStandaloneSetupGenerated {

	public static void doSetup() {
		new TestSuiteStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
