/**
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.testSuite;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Force</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.mdh.dva501.testsuite.testSuite.Force#getValue <em>Value</em>}</li>
 *   <li>{@link se.mdh.dva501.testsuite.testSuite.Force#getProductValueExceptions <em>Product Value Exceptions</em>}</li>
 * </ul>
 *
 * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getForce()
 * @model
 * @generated
 */
public interface Force extends Step
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Value)
   * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getForce_Value()
   * @model containment="true"
   * @generated
   */
  Value getValue();

  /**
   * Sets the value of the '{@link se.mdh.dva501.testsuite.testSuite.Force#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Value value);

  /**
   * Returns the value of the '<em><b>Product Value Exceptions</b></em>' containment reference list.
   * The list contents are of type {@link se.mdh.dva501.testsuite.testSuite.ProductValueException}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Product Value Exceptions</em>' containment reference list.
   * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getForce_ProductValueExceptions()
   * @model containment="true"
   * @generated
   */
  EList<ProductValueException> getProductValueExceptions();

} // Force
