/**
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.testSuite;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Product Exception</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.mdh.dva501.testsuite.testSuite.ProductException#getProductName <em>Product Name</em>}</li>
 * </ul>
 *
 * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getProductException()
 * @model
 * @generated
 */
public interface ProductException extends EObject
{
  /**
   * Returns the value of the '<em><b>Product Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Product Name</em>' attribute.
   * @see #setProductName(String)
   * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getProductException_ProductName()
   * @model
   * @generated
   */
  String getProductName();

  /**
   * Sets the value of the '{@link se.mdh.dva501.testsuite.testSuite.ProductException#getProductName <em>Product Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Product Name</em>' attribute.
   * @see #getProductName()
   * @generated
   */
  void setProductName(String value);

} // ProductException
