/**
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.testSuite;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Product Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.mdh.dva501.testsuite.testSuite.ProductStep#getProductSignal <em>Product Signal</em>}</li>
 *   <li>{@link se.mdh.dva501.testsuite.testSuite.ProductStep#getSystem <em>System</em>}</li>
 * </ul>
 *
 * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getProductStep()
 * @model
 * @generated
 */
public interface ProductStep extends EObject
{
  /**
   * Returns the value of the '<em><b>Product Signal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Product Signal</em>' containment reference.
   * @see #setProductSignal(Signal)
   * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getProductStep_ProductSignal()
   * @model containment="true"
   * @generated
   */
  Signal getProductSignal();

  /**
   * Sets the value of the '{@link se.mdh.dva501.testsuite.testSuite.ProductStep#getProductSignal <em>Product Signal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Product Signal</em>' containment reference.
   * @see #getProductSignal()
   * @generated
   */
  void setProductSignal(Signal value);

  /**
   * Returns the value of the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>System</em>' attribute.
   * @see #setSystem(String)
   * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getProductStep_System()
   * @model
   * @generated
   */
  String getSystem();

  /**
   * Sets the value of the '{@link se.mdh.dva501.testsuite.testSuite.ProductStep#getSystem <em>System</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>System</em>' attribute.
   * @see #getSystem()
   * @generated
   */
  void setSystem(String value);

} // ProductStep
