/**
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.testSuite;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Product Unforce</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getProductUnforce()
 * @model
 * @generated
 */
public interface ProductUnforce extends ProductStep
{
} // ProductUnforce
