/**
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.testSuite;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Suite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.mdh.dva501.testsuite.testSuite.TestSuite#getTestCases <em>Test Cases</em>}</li>
 *   <li>{@link se.mdh.dva501.testsuite.testSuite.TestSuite#getProductTestCases <em>Product Test Cases</em>}</li>
 * </ul>
 *
 * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getTestSuite()
 * @model
 * @generated
 */
public interface TestSuite extends EObject
{
  /**
   * Returns the value of the '<em><b>Test Cases</b></em>' containment reference list.
   * The list contents are of type {@link se.mdh.dva501.testsuite.testSuite.TestCase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test Cases</em>' containment reference list.
   * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getTestSuite_TestCases()
   * @model containment="true"
   * @generated
   */
  EList<TestCase> getTestCases();

  /**
   * Returns the value of the '<em><b>Product Test Cases</b></em>' containment reference list.
   * The list contents are of type {@link se.mdh.dva501.testsuite.testSuite.ProductTestCase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Product Test Cases</em>' containment reference list.
   * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getTestSuite_ProductTestCases()
   * @model containment="true"
   * @generated
   */
  EList<ProductTestCase> getProductTestCases();

} // TestSuite
