/**
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.testSuite;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.mdh.dva501.testsuite.testSuite.TestCase#getName <em>Name</em>}</li>
 *   <li>{@link se.mdh.dva501.testsuite.testSuite.TestCase#getGenericFunction <em>Generic Function</em>}</li>
 *   <li>{@link se.mdh.dva501.testsuite.testSuite.TestCase#getProductException <em>Product Exception</em>}</li>
 *   <li>{@link se.mdh.dva501.testsuite.testSuite.TestCase#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getTestCase()
 * @model
 * @generated
 */
public interface TestCase extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getTestCase_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link se.mdh.dva501.testsuite.testSuite.TestCase#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Generic Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generic Function</em>' attribute.
   * @see #setGenericFunction(String)
   * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getTestCase_GenericFunction()
   * @model
   * @generated
   */
  String getGenericFunction();

  /**
   * Sets the value of the '{@link se.mdh.dva501.testsuite.testSuite.TestCase#getGenericFunction <em>Generic Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generic Function</em>' attribute.
   * @see #getGenericFunction()
   * @generated
   */
  void setGenericFunction(String value);

  /**
   * Returns the value of the '<em><b>Product Exception</b></em>' containment reference list.
   * The list contents are of type {@link se.mdh.dva501.testsuite.testSuite.ProductException}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Product Exception</em>' containment reference list.
   * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getTestCase_ProductException()
   * @model containment="true"
   * @generated
   */
  EList<ProductException> getProductException();

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link se.mdh.dva501.testsuite.testSuite.Step}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getTestCase_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Step> getSteps();

} // TestCase
