/**
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.testSuite;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see se.mdh.dva501.testsuite.testSuite.TestSuiteFactory
 * @model kind="package"
 * @generated
 */
public interface TestSuitePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "testSuite";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mdh.se/dva501/testsuite/TestSuite";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "testSuite";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TestSuitePackage eINSTANCE = se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl.init();

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.TestSuiteImpl <em>Test Suite</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuiteImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getTestSuite()
   * @generated
   */
  int TEST_SUITE = 0;

  /**
   * The feature id for the '<em><b>Test Cases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE__TEST_CASES = 0;

  /**
   * The feature id for the '<em><b>Product Test Cases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE__PRODUCT_TEST_CASES = 1;

  /**
   * The number of structural features of the '<em>Test Suite</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_SUITE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.TestCaseImpl <em>Test Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestCaseImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getTestCase()
   * @generated
   */
  int TEST_CASE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__NAME = 0;

  /**
   * The feature id for the '<em><b>Generic Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__GENERIC_FUNCTION = 1;

  /**
   * The feature id for the '<em><b>Product Exception</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__PRODUCT_EXCEPTION = 2;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__STEPS = 3;

  /**
   * The number of structural features of the '<em>Test Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductExceptionImpl <em>Product Exception</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.ProductExceptionImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductException()
   * @generated
   */
  int PRODUCT_EXCEPTION = 2;

  /**
   * The feature id for the '<em><b>Product Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_EXCEPTION__PRODUCT_NAME = 0;

  /**
   * The number of structural features of the '<em>Product Exception</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_EXCEPTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.StepImpl <em>Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.StepImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getStep()
   * @generated
   */
  int STEP = 3;

  /**
   * The feature id for the '<em><b>Generic Signal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__GENERIC_SIGNAL = 0;

  /**
   * The number of structural features of the '<em>Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.SetImpl <em>Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.SetImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getSet()
   * @generated
   */
  int SET = 4;

  /**
   * The feature id for the '<em><b>Generic Signal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET__GENERIC_SIGNAL = STEP__GENERIC_SIGNAL;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET__VALUE = STEP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Product Value Exceptions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET__PRODUCT_VALUE_EXCEPTIONS = STEP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_FEATURE_COUNT = STEP_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ForceImpl <em>Force</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.ForceImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getForce()
   * @generated
   */
  int FORCE = 5;

  /**
   * The feature id for the '<em><b>Generic Signal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORCE__GENERIC_SIGNAL = STEP__GENERIC_SIGNAL;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORCE__VALUE = STEP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Product Value Exceptions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORCE__PRODUCT_VALUE_EXCEPTIONS = STEP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Force</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORCE_FEATURE_COUNT = STEP_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.UnforceImpl <em>Unforce</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.UnforceImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getUnforce()
   * @generated
   */
  int UNFORCE = 6;

  /**
   * The feature id for the '<em><b>Generic Signal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNFORCE__GENERIC_SIGNAL = STEP__GENERIC_SIGNAL;

  /**
   * The number of structural features of the '<em>Unforce</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNFORCE_FEATURE_COUNT = STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.CheckImpl <em>Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.CheckImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getCheck()
   * @generated
   */
  int CHECK = 7;

  /**
   * The feature id for the '<em><b>Generic Signal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__GENERIC_SIGNAL = STEP__GENERIC_SIGNAL;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__VALUE = STEP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Product Value Exceptions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__PRODUCT_VALUE_EXCEPTIONS = STEP_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Timeout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__TIMEOUT = STEP_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_FEATURE_COUNT = STEP_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductValueExceptionImpl <em>Product Value Exception</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.ProductValueExceptionImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductValueException()
   * @generated
   */
  int PRODUCT_VALUE_EXCEPTION = 8;

  /**
   * The feature id for the '<em><b>Product Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_VALUE_EXCEPTION__PRODUCT_NAME = 0;

  /**
   * The feature id for the '<em><b>Product Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_VALUE_EXCEPTION__PRODUCT_VALUE = 1;

  /**
   * The number of structural features of the '<em>Product Value Exception</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_VALUE_EXCEPTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.SignalImpl <em>Signal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.SignalImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getSignal()
   * @generated
   */
  int SIGNAL = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL__NAME = 0;

  /**
   * The number of structural features of the '<em>Signal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.ValueImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getValue()
   * @generated
   */
  int VALUE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__NAME = 0;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.TimeoutImpl <em>Timeout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.TimeoutImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getTimeout()
   * @generated
   */
  int TIMEOUT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMEOUT__NAME = 0;

  /**
   * The number of structural features of the '<em>Timeout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMEOUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductTestCaseImpl <em>Product Test Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.ProductTestCaseImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductTestCase()
   * @generated
   */
  int PRODUCT_TEST_CASE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_TEST_CASE__NAME = 0;

  /**
   * The feature id for the '<em><b>Product Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_TEST_CASE__PRODUCT_NAME = 1;

  /**
   * The feature id for the '<em><b>Product Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_TEST_CASE__PRODUCT_STEPS = 2;

  /**
   * The number of structural features of the '<em>Product Test Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_TEST_CASE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductStepImpl <em>Product Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.ProductStepImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductStep()
   * @generated
   */
  int PRODUCT_STEP = 13;

  /**
   * The feature id for the '<em><b>Product Signal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_STEP__PRODUCT_SIGNAL = 0;

  /**
   * The feature id for the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_STEP__SYSTEM = 1;

  /**
   * The number of structural features of the '<em>Product Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_STEP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductSetImpl <em>Product Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.ProductSetImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductSet()
   * @generated
   */
  int PRODUCT_SET = 14;

  /**
   * The feature id for the '<em><b>Product Signal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_SET__PRODUCT_SIGNAL = PRODUCT_STEP__PRODUCT_SIGNAL;

  /**
   * The feature id for the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_SET__SYSTEM = PRODUCT_STEP__SYSTEM;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_SET__VALUE = PRODUCT_STEP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Product Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_SET_FEATURE_COUNT = PRODUCT_STEP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductForceImpl <em>Product Force</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.ProductForceImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductForce()
   * @generated
   */
  int PRODUCT_FORCE = 15;

  /**
   * The feature id for the '<em><b>Product Signal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_FORCE__PRODUCT_SIGNAL = PRODUCT_STEP__PRODUCT_SIGNAL;

  /**
   * The feature id for the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_FORCE__SYSTEM = PRODUCT_STEP__SYSTEM;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_FORCE__VALUE = PRODUCT_STEP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Product Force</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_FORCE_FEATURE_COUNT = PRODUCT_STEP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductUnforceImpl <em>Product Unforce</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.ProductUnforceImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductUnforce()
   * @generated
   */
  int PRODUCT_UNFORCE = 16;

  /**
   * The feature id for the '<em><b>Product Signal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_UNFORCE__PRODUCT_SIGNAL = PRODUCT_STEP__PRODUCT_SIGNAL;

  /**
   * The feature id for the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_UNFORCE__SYSTEM = PRODUCT_STEP__SYSTEM;

  /**
   * The number of structural features of the '<em>Product Unforce</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_UNFORCE_FEATURE_COUNT = PRODUCT_STEP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductCheckImpl <em>Product Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see se.mdh.dva501.testsuite.testSuite.impl.ProductCheckImpl
   * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductCheck()
   * @generated
   */
  int PRODUCT_CHECK = 17;

  /**
   * The feature id for the '<em><b>Product Signal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_CHECK__PRODUCT_SIGNAL = PRODUCT_STEP__PRODUCT_SIGNAL;

  /**
   * The feature id for the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_CHECK__SYSTEM = PRODUCT_STEP__SYSTEM;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_CHECK__VALUE = PRODUCT_STEP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Timeout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_CHECK__TIMEOUT = PRODUCT_STEP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Product Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_CHECK_FEATURE_COUNT = PRODUCT_STEP_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.TestSuite <em>Test Suite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Suite</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.TestSuite
   * @generated
   */
  EClass getTestSuite();

  /**
   * Returns the meta object for the containment reference list '{@link se.mdh.dva501.testsuite.testSuite.TestSuite#getTestCases <em>Test Cases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Test Cases</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.TestSuite#getTestCases()
   * @see #getTestSuite()
   * @generated
   */
  EReference getTestSuite_TestCases();

  /**
   * Returns the meta object for the containment reference list '{@link se.mdh.dva501.testsuite.testSuite.TestSuite#getProductTestCases <em>Product Test Cases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Product Test Cases</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.TestSuite#getProductTestCases()
   * @see #getTestSuite()
   * @generated
   */
  EReference getTestSuite_ProductTestCases();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.TestCase <em>Test Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Case</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.TestCase
   * @generated
   */
  EClass getTestCase();

  /**
   * Returns the meta object for the attribute '{@link se.mdh.dva501.testsuite.testSuite.TestCase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.TestCase#getName()
   * @see #getTestCase()
   * @generated
   */
  EAttribute getTestCase_Name();

  /**
   * Returns the meta object for the attribute '{@link se.mdh.dva501.testsuite.testSuite.TestCase#getGenericFunction <em>Generic Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Generic Function</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.TestCase#getGenericFunction()
   * @see #getTestCase()
   * @generated
   */
  EAttribute getTestCase_GenericFunction();

  /**
   * Returns the meta object for the containment reference list '{@link se.mdh.dva501.testsuite.testSuite.TestCase#getProductException <em>Product Exception</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Product Exception</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.TestCase#getProductException()
   * @see #getTestCase()
   * @generated
   */
  EReference getTestCase_ProductException();

  /**
   * Returns the meta object for the containment reference list '{@link se.mdh.dva501.testsuite.testSuite.TestCase#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.TestCase#getSteps()
   * @see #getTestCase()
   * @generated
   */
  EReference getTestCase_Steps();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.ProductException <em>Product Exception</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product Exception</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductException
   * @generated
   */
  EClass getProductException();

  /**
   * Returns the meta object for the attribute '{@link se.mdh.dva501.testsuite.testSuite.ProductException#getProductName <em>Product Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Product Name</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductException#getProductName()
   * @see #getProductException()
   * @generated
   */
  EAttribute getProductException_ProductName();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.Step <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Step
   * @generated
   */
  EClass getStep();

  /**
   * Returns the meta object for the containment reference '{@link se.mdh.dva501.testsuite.testSuite.Step#getGenericSignal <em>Generic Signal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Generic Signal</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Step#getGenericSignal()
   * @see #getStep()
   * @generated
   */
  EReference getStep_GenericSignal();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.Set <em>Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Set</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Set
   * @generated
   */
  EClass getSet();

  /**
   * Returns the meta object for the containment reference '{@link se.mdh.dva501.testsuite.testSuite.Set#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Set#getValue()
   * @see #getSet()
   * @generated
   */
  EReference getSet_Value();

  /**
   * Returns the meta object for the containment reference list '{@link se.mdh.dva501.testsuite.testSuite.Set#getProductValueExceptions <em>Product Value Exceptions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Product Value Exceptions</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Set#getProductValueExceptions()
   * @see #getSet()
   * @generated
   */
  EReference getSet_ProductValueExceptions();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.Force <em>Force</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Force</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Force
   * @generated
   */
  EClass getForce();

  /**
   * Returns the meta object for the containment reference '{@link se.mdh.dva501.testsuite.testSuite.Force#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Force#getValue()
   * @see #getForce()
   * @generated
   */
  EReference getForce_Value();

  /**
   * Returns the meta object for the containment reference list '{@link se.mdh.dva501.testsuite.testSuite.Force#getProductValueExceptions <em>Product Value Exceptions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Product Value Exceptions</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Force#getProductValueExceptions()
   * @see #getForce()
   * @generated
   */
  EReference getForce_ProductValueExceptions();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.Unforce <em>Unforce</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unforce</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Unforce
   * @generated
   */
  EClass getUnforce();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.Check <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Check
   * @generated
   */
  EClass getCheck();

  /**
   * Returns the meta object for the containment reference '{@link se.mdh.dva501.testsuite.testSuite.Check#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Check#getValue()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Value();

  /**
   * Returns the meta object for the containment reference list '{@link se.mdh.dva501.testsuite.testSuite.Check#getProductValueExceptions <em>Product Value Exceptions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Product Value Exceptions</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Check#getProductValueExceptions()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_ProductValueExceptions();

  /**
   * Returns the meta object for the containment reference '{@link se.mdh.dva501.testsuite.testSuite.Check#getTimeout <em>Timeout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Timeout</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Check#getTimeout()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Timeout();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.ProductValueException <em>Product Value Exception</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product Value Exception</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductValueException
   * @generated
   */
  EClass getProductValueException();

  /**
   * Returns the meta object for the attribute '{@link se.mdh.dva501.testsuite.testSuite.ProductValueException#getProductName <em>Product Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Product Name</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductValueException#getProductName()
   * @see #getProductValueException()
   * @generated
   */
  EAttribute getProductValueException_ProductName();

  /**
   * Returns the meta object for the attribute '{@link se.mdh.dva501.testsuite.testSuite.ProductValueException#getProductValue <em>Product Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Product Value</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductValueException#getProductValue()
   * @see #getProductValueException()
   * @generated
   */
  EAttribute getProductValueException_ProductValue();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.Signal <em>Signal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Signal</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Signal
   * @generated
   */
  EClass getSignal();

  /**
   * Returns the meta object for the attribute '{@link se.mdh.dva501.testsuite.testSuite.Signal#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Signal#getName()
   * @see #getSignal()
   * @generated
   */
  EAttribute getSignal_Name();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for the attribute '{@link se.mdh.dva501.testsuite.testSuite.Value#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Value#getName()
   * @see #getValue()
   * @generated
   */
  EAttribute getValue_Name();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.Timeout <em>Timeout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Timeout</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Timeout
   * @generated
   */
  EClass getTimeout();

  /**
   * Returns the meta object for the attribute '{@link se.mdh.dva501.testsuite.testSuite.Timeout#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.Timeout#getName()
   * @see #getTimeout()
   * @generated
   */
  EAttribute getTimeout_Name();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.ProductTestCase <em>Product Test Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product Test Case</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductTestCase
   * @generated
   */
  EClass getProductTestCase();

  /**
   * Returns the meta object for the attribute '{@link se.mdh.dva501.testsuite.testSuite.ProductTestCase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductTestCase#getName()
   * @see #getProductTestCase()
   * @generated
   */
  EAttribute getProductTestCase_Name();

  /**
   * Returns the meta object for the attribute '{@link se.mdh.dva501.testsuite.testSuite.ProductTestCase#getProductName <em>Product Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Product Name</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductTestCase#getProductName()
   * @see #getProductTestCase()
   * @generated
   */
  EAttribute getProductTestCase_ProductName();

  /**
   * Returns the meta object for the containment reference list '{@link se.mdh.dva501.testsuite.testSuite.ProductTestCase#getProductSteps <em>Product Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Product Steps</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductTestCase#getProductSteps()
   * @see #getProductTestCase()
   * @generated
   */
  EReference getProductTestCase_ProductSteps();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.ProductStep <em>Product Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product Step</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductStep
   * @generated
   */
  EClass getProductStep();

  /**
   * Returns the meta object for the containment reference '{@link se.mdh.dva501.testsuite.testSuite.ProductStep#getProductSignal <em>Product Signal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Product Signal</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductStep#getProductSignal()
   * @see #getProductStep()
   * @generated
   */
  EReference getProductStep_ProductSignal();

  /**
   * Returns the meta object for the attribute '{@link se.mdh.dva501.testsuite.testSuite.ProductStep#getSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>System</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductStep#getSystem()
   * @see #getProductStep()
   * @generated
   */
  EAttribute getProductStep_System();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.ProductSet <em>Product Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product Set</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductSet
   * @generated
   */
  EClass getProductSet();

  /**
   * Returns the meta object for the containment reference '{@link se.mdh.dva501.testsuite.testSuite.ProductSet#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductSet#getValue()
   * @see #getProductSet()
   * @generated
   */
  EReference getProductSet_Value();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.ProductForce <em>Product Force</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product Force</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductForce
   * @generated
   */
  EClass getProductForce();

  /**
   * Returns the meta object for the containment reference '{@link se.mdh.dva501.testsuite.testSuite.ProductForce#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductForce#getValue()
   * @see #getProductForce()
   * @generated
   */
  EReference getProductForce_Value();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.ProductUnforce <em>Product Unforce</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product Unforce</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductUnforce
   * @generated
   */
  EClass getProductUnforce();

  /**
   * Returns the meta object for class '{@link se.mdh.dva501.testsuite.testSuite.ProductCheck <em>Product Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product Check</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductCheck
   * @generated
   */
  EClass getProductCheck();

  /**
   * Returns the meta object for the containment reference '{@link se.mdh.dva501.testsuite.testSuite.ProductCheck#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductCheck#getValue()
   * @see #getProductCheck()
   * @generated
   */
  EReference getProductCheck_Value();

  /**
   * Returns the meta object for the containment reference '{@link se.mdh.dva501.testsuite.testSuite.ProductCheck#getTimeout <em>Timeout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Timeout</em>'.
   * @see se.mdh.dva501.testsuite.testSuite.ProductCheck#getTimeout()
   * @see #getProductCheck()
   * @generated
   */
  EReference getProductCheck_Timeout();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TestSuiteFactory getTestSuiteFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.TestSuiteImpl <em>Test Suite</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuiteImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getTestSuite()
     * @generated
     */
    EClass TEST_SUITE = eINSTANCE.getTestSuite();

    /**
     * The meta object literal for the '<em><b>Test Cases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_SUITE__TEST_CASES = eINSTANCE.getTestSuite_TestCases();

    /**
     * The meta object literal for the '<em><b>Product Test Cases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_SUITE__PRODUCT_TEST_CASES = eINSTANCE.getTestSuite_ProductTestCases();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.TestCaseImpl <em>Test Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestCaseImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getTestCase()
     * @generated
     */
    EClass TEST_CASE = eINSTANCE.getTestCase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_CASE__NAME = eINSTANCE.getTestCase_Name();

    /**
     * The meta object literal for the '<em><b>Generic Function</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_CASE__GENERIC_FUNCTION = eINSTANCE.getTestCase_GenericFunction();

    /**
     * The meta object literal for the '<em><b>Product Exception</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_CASE__PRODUCT_EXCEPTION = eINSTANCE.getTestCase_ProductException();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_CASE__STEPS = eINSTANCE.getTestCase_Steps();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductExceptionImpl <em>Product Exception</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.ProductExceptionImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductException()
     * @generated
     */
    EClass PRODUCT_EXCEPTION = eINSTANCE.getProductException();

    /**
     * The meta object literal for the '<em><b>Product Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCT_EXCEPTION__PRODUCT_NAME = eINSTANCE.getProductException_ProductName();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.StepImpl <em>Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.StepImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getStep()
     * @generated
     */
    EClass STEP = eINSTANCE.getStep();

    /**
     * The meta object literal for the '<em><b>Generic Signal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__GENERIC_SIGNAL = eINSTANCE.getStep_GenericSignal();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.SetImpl <em>Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.SetImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getSet()
     * @generated
     */
    EClass SET = eINSTANCE.getSet();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET__VALUE = eINSTANCE.getSet_Value();

    /**
     * The meta object literal for the '<em><b>Product Value Exceptions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET__PRODUCT_VALUE_EXCEPTIONS = eINSTANCE.getSet_ProductValueExceptions();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ForceImpl <em>Force</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.ForceImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getForce()
     * @generated
     */
    EClass FORCE = eINSTANCE.getForce();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORCE__VALUE = eINSTANCE.getForce_Value();

    /**
     * The meta object literal for the '<em><b>Product Value Exceptions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORCE__PRODUCT_VALUE_EXCEPTIONS = eINSTANCE.getForce_ProductValueExceptions();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.UnforceImpl <em>Unforce</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.UnforceImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getUnforce()
     * @generated
     */
    EClass UNFORCE = eINSTANCE.getUnforce();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.CheckImpl <em>Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.CheckImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getCheck()
     * @generated
     */
    EClass CHECK = eINSTANCE.getCheck();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__VALUE = eINSTANCE.getCheck_Value();

    /**
     * The meta object literal for the '<em><b>Product Value Exceptions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__PRODUCT_VALUE_EXCEPTIONS = eINSTANCE.getCheck_ProductValueExceptions();

    /**
     * The meta object literal for the '<em><b>Timeout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__TIMEOUT = eINSTANCE.getCheck_Timeout();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductValueExceptionImpl <em>Product Value Exception</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.ProductValueExceptionImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductValueException()
     * @generated
     */
    EClass PRODUCT_VALUE_EXCEPTION = eINSTANCE.getProductValueException();

    /**
     * The meta object literal for the '<em><b>Product Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCT_VALUE_EXCEPTION__PRODUCT_NAME = eINSTANCE.getProductValueException_ProductName();

    /**
     * The meta object literal for the '<em><b>Product Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCT_VALUE_EXCEPTION__PRODUCT_VALUE = eINSTANCE.getProductValueException_ProductValue();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.SignalImpl <em>Signal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.SignalImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getSignal()
     * @generated
     */
    EClass SIGNAL = eINSTANCE.getSignal();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIGNAL__NAME = eINSTANCE.getSignal_Name();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.ValueImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__NAME = eINSTANCE.getValue_Name();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.TimeoutImpl <em>Timeout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.TimeoutImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getTimeout()
     * @generated
     */
    EClass TIMEOUT = eINSTANCE.getTimeout();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIMEOUT__NAME = eINSTANCE.getTimeout_Name();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductTestCaseImpl <em>Product Test Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.ProductTestCaseImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductTestCase()
     * @generated
     */
    EClass PRODUCT_TEST_CASE = eINSTANCE.getProductTestCase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCT_TEST_CASE__NAME = eINSTANCE.getProductTestCase_Name();

    /**
     * The meta object literal for the '<em><b>Product Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCT_TEST_CASE__PRODUCT_NAME = eINSTANCE.getProductTestCase_ProductName();

    /**
     * The meta object literal for the '<em><b>Product Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCT_TEST_CASE__PRODUCT_STEPS = eINSTANCE.getProductTestCase_ProductSteps();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductStepImpl <em>Product Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.ProductStepImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductStep()
     * @generated
     */
    EClass PRODUCT_STEP = eINSTANCE.getProductStep();

    /**
     * The meta object literal for the '<em><b>Product Signal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCT_STEP__PRODUCT_SIGNAL = eINSTANCE.getProductStep_ProductSignal();

    /**
     * The meta object literal for the '<em><b>System</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCT_STEP__SYSTEM = eINSTANCE.getProductStep_System();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductSetImpl <em>Product Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.ProductSetImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductSet()
     * @generated
     */
    EClass PRODUCT_SET = eINSTANCE.getProductSet();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCT_SET__VALUE = eINSTANCE.getProductSet_Value();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductForceImpl <em>Product Force</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.ProductForceImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductForce()
     * @generated
     */
    EClass PRODUCT_FORCE = eINSTANCE.getProductForce();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCT_FORCE__VALUE = eINSTANCE.getProductForce_Value();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductUnforceImpl <em>Product Unforce</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.ProductUnforceImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductUnforce()
     * @generated
     */
    EClass PRODUCT_UNFORCE = eINSTANCE.getProductUnforce();

    /**
     * The meta object literal for the '{@link se.mdh.dva501.testsuite.testSuite.impl.ProductCheckImpl <em>Product Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see se.mdh.dva501.testsuite.testSuite.impl.ProductCheckImpl
     * @see se.mdh.dva501.testsuite.testSuite.impl.TestSuitePackageImpl#getProductCheck()
     * @generated
     */
    EClass PRODUCT_CHECK = eINSTANCE.getProductCheck();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCT_CHECK__VALUE = eINSTANCE.getProductCheck_Value();

    /**
     * The meta object literal for the '<em><b>Timeout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCT_CHECK__TIMEOUT = eINSTANCE.getProductCheck_Timeout();

  }

} //TestSuitePackage
