/**
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.testSuite;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unforce</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see se.mdh.dva501.testsuite.testSuite.TestSuitePackage#getUnforce()
 * @model
 * @generated
 */
public interface Unforce extends Step
{
} // Unforce
