/**
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.testSuite.impl;

import org.eclipse.emf.ecore.EClass;

import se.mdh.dva501.testsuite.testSuite.ProductUnforce;
import se.mdh.dva501.testsuite.testSuite.TestSuitePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Product Unforce</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ProductUnforceImpl extends ProductStepImpl implements ProductUnforce
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProductUnforceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TestSuitePackage.Literals.PRODUCT_UNFORCE;
  }

} //ProductUnforceImpl
