/**
 * generated by Xtext 2.21.0
 */
package se.mdh.dva501.testsuite.testSuite.impl;

import org.eclipse.emf.ecore.EClass;

import se.mdh.dva501.testsuite.testSuite.TestSuitePackage;
import se.mdh.dva501.testsuite.testSuite.Unforce;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Unforce</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UnforceImpl extends StepImpl implements Unforce
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UnforceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TestSuitePackage.Literals.UNFORCE;
  }

} //UnforceImpl
